# Generated by Django 3.2 on 2021-04-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210413_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
